### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by AT0mo** [knoxfighter/arcdps-killproof.me-plugin#16]
Whenever I join a big group let's say Dragonstorm, it loads all the characters, that doesn't clear itself after I leave the squad meaning When I join a new party e.g. for fractals, I cannot use the addon because I still only see the names of the bigger group. Clicking 'Clear chache' doesn't help either. I'm also using unoficial extras.

**Comment by knoxfighter** [comment]
That is a bug in the unofficial extras, which will be fixed with the next release of that :)

**Comment by hanakocz** [comment]
Hello,
Things do get gradually worse and worse recently. Nowadays not only it does not clear the previous squads, it also starts with complete random people (well from one of the guilds I am member of), and even starts happening that the button to get your ID either won't appear, or actually gives you ID of someone else. 

Is there any chance to get those cache things fixed in near future, before it starts to do even more unwanted things? Would be really apreciated, thanks.

**Comment by knoxfighter** [comment]
unofficial extras was updated yesterday, update it and it will work correctly again.
