### ISSUE TITLE
Game crash after open killproof.me addon

### ISSUE THREAD

**Issue by sryzhov** [knoxfighter/arcdps-killproof.me-plugin#19]
Hello! After July 18 i always catch game crash when open killproof.me addon tab in game. Help pls, how i can solve this problem?

**Comment by knoxfighter** [comment]
I heard about that error on discord as well, the easiest way to fix it, is to switch to dx11. Since i am not able to reproduce that error i am not able to fix it.

**Comment by sryzhov** [comment]
> I heard about that error on discord as well, the easiest way to fix it, is to switch to dx11. Since i am not able to reproduce that error i am not able to fix it.

Thank you! Change to DX11 solve problem for me.

**Comment by DeaJae** [comment]
Had this crash too, and while switching to dx11 does solve it, I don't know if this would be a great option for me due to old hardware.
I have found a log file for the crash in dx9 mode.
[arcdps_lastcrash.log](https://github.com/knoxfighter/arcdps-killproof.me-plugin/files/9446288/arcdps_lastcrash.log)

**Comment by knoxfighter** [comment]
yes, i produce a crash within the gw2 renderer when using dx9. It is a lot of effort to fix it and since dx9 is deprecated, i will not fix it :(
Just use dx11 in the future,
